/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Entity.PagamentoAvista;
import Model.Entity.PagamentoFinanciado;
import Model.Repository.FormaPagamentoRepository;
import Model.Repository.PagamentoAvistaRepository;
import Model.Repository.PagamentoFinanciadoRepository;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alyssonp
 */
public class GerenciarFormasPagamento extends javax.swing.JFrame {
    private static final PagamentoAvistaRepository avistaRepository = new PagamentoAvistaRepository();
    private static final PagamentoFinanciadoRepository finaciadoRepository = new PagamentoFinanciadoRepository();
    private static final FormaPagamentoRepository formaPagamento = new FormaPagamentoRepository();
    
    private CardLayout cl;
    private Color colorEnable, colorDisabled;
    /**
     * Creates new form CriarFormaPagamento
     */
    public GerenciarFormasPagamento() {
        initComponents();
        colorEnable = new Color(237,114,114);
        colorDisabled = new Color(212,20,20);
        cl = (CardLayout) Main.getLayout();
        
        btnAvistaMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAvista = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnFinaciado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        PagamentoAvista = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputNomePagamentoAvista = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputPercentualDesconto = new javax.swing.JTextField();
        btnLimparCamposAvista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAvista = new javax.swing.JTable();
        btnCriarAvista = new javax.swing.JButton();
        btnAtualizarAvista = new javax.swing.JButton();
        btnExcluirAvista = new javax.swing.JButton();
        btnDesselecionarAvista = new javax.swing.JButton();
        PagamentoFinanciado = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputNomePagamentoFinanciado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        inputTaxaJuros = new javax.swing.JTextField();
        inputQuantidadeParcela = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnLimparCamposFinanciado = new javax.swing.JButton();
        btnCriarFinanciado = new javax.swing.JButton();
        btnAtualizarFinanciado = new javax.swing.JButton();
        btnExcluirFinanciado = new javax.swing.JButton();
        btnDesselecionarFinanciado = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaFinanciado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SHOP MOTROS - GERNCIAMENTO DE FORMAS DE PAGAMENTO");

        navbar.setBackground(new java.awt.Color(212, 20, 20));
        navbar.setPreferredSize(new java.awt.Dimension(178, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Shop Motors");

        btnAvista.setBackground(new java.awt.Color(237, 114, 114));
        btnAvista.setToolTipText("Carros"); // NOI18N
        btnAvista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAvistaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A vista");

        javax.swing.GroupLayout btnAvistaLayout = new javax.swing.GroupLayout(btnAvista);
        btnAvista.setLayout(btnAvistaLayout);
        btnAvistaLayout.setHorizontalGroup(
            btnAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAvistaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAvistaLayout.setVerticalGroup(
            btnAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAvistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFinaciado.setBackground(new java.awt.Color(212, 20, 20));
        btnFinaciado.setToolTipText("Motos");
        btnFinaciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinaciadoMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Financiado");

        javax.swing.GroupLayout btnFinaciadoLayout = new javax.swing.GroupLayout(btnFinaciado);
        btnFinaciado.setLayout(btnFinaciadoLayout);
        btnFinaciadoLayout.setHorizontalGroup(
            btnFinaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinaciadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFinaciadoLayout.setVerticalGroup(
            btnFinaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinaciadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(btnAvista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinaciado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnAvista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFinaciado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new java.awt.CardLayout());

        PagamentoAvista.setBackground(new java.awt.Color(255, 255, 255));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel41.setText("Pagamento A vista");

        jLabel8.setText("Nome do pagamento:");

        jLabel9.setText("Percentual de desconto:");

        inputPercentualDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPercentualDescontoKeyTyped(evt);
            }
        });

        btnLimparCamposAvista.setText("Limpar Campos");
        btnLimparCamposAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposAvistaActionPerformed(evt);
            }
        });

        tabelaAvista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome Pagamento", "Percentual Desconto"
            }
        ));
        tabelaAvista.setSelectionBackground(new java.awt.Color(128, 26, 26));
        tabelaAvista.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaAvista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAvistaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAvista);

        btnCriarAvista.setText("Criar");
        btnCriarAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAvistaActionPerformed(evt);
            }
        });

        btnAtualizarAvista.setText("Atualizar");
        btnAtualizarAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarAvistaActionPerformed(evt);
            }
        });

        btnExcluirAvista.setText("Excluir");
        btnExcluirAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAvistaActionPerformed(evt);
            }
        });

        btnDesselecionarAvista.setText("Desselecionar");
        btnDesselecionarAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesselecionarAvistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PagamentoAvistaLayout = new javax.swing.GroupLayout(PagamentoAvista);
        PagamentoAvista.setLayout(PagamentoAvistaLayout);
        PagamentoAvistaLayout.setHorizontalGroup(
            PagamentoAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoAvistaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PagamentoAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagamentoAvistaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNomePagamentoAvista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPercentualDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparCamposAvista))
                    .addComponent(jLabel41)
                    .addGroup(PagamentoAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PagamentoAvistaLayout.createSequentialGroup()
                            .addComponent(btnCriarAvista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAtualizarAvista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluirAvista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDesselecionarAvista))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PagamentoAvistaLayout.setVerticalGroup(
            PagamentoAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoAvistaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PagamentoAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputNomePagamentoAvista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(inputPercentualDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCamposAvista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PagamentoAvistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesselecionarAvista)
                    .addComponent(btnCriarAvista)
                    .addComponent(btnAtualizarAvista)
                    .addComponent(btnExcluirAvista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        Main.add(PagamentoAvista, "cardAvista");

        PagamentoFinanciado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setText("Pagamento Financiado");

        jLabel11.setText("Nome do pagamento:");

        jLabel12.setText("Taxa Juros");

        jLabel13.setText("Quantidade Parcelas");

        btnLimparCamposFinanciado.setText("Limpar Campos");
        btnLimparCamposFinanciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposFinanciadoActionPerformed(evt);
            }
        });

        btnCriarFinanciado.setText("Criar");
        btnCriarFinanciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarFinanciadoActionPerformed(evt);
            }
        });

        btnAtualizarFinanciado.setText("Atualizar");
        btnAtualizarFinanciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarFinanciadoActionPerformed(evt);
            }
        });

        btnExcluirFinanciado.setText("Excluir");
        btnExcluirFinanciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFinanciadoActionPerformed(evt);
            }
        });

        btnDesselecionarFinanciado.setText("Desselecionar");
        btnDesselecionarFinanciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesselecionarFinanciadoActionPerformed(evt);
            }
        });

        tabelaFinanciado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome Pagamento", "Taxa Juros", "Quanrtidade Parcelas"
            }
        ));
        tabelaFinanciado.setSelectionBackground(new java.awt.Color(128, 26, 26));
        tabelaFinanciado.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaFinanciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFinanciadoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaFinanciado);

        javax.swing.GroupLayout PagamentoFinanciadoLayout = new javax.swing.GroupLayout(PagamentoFinanciado);
        PagamentoFinanciado.setLayout(PagamentoFinanciadoLayout);
        PagamentoFinanciadoLayout.setHorizontalGroup(
            PagamentoFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoFinanciadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PagamentoFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagamentoFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PagamentoFinanciadoLayout.createSequentialGroup()
                            .addComponent(btnCriarFinanciado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAtualizarFinanciado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluirFinanciado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDesselecionarFinanciado))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PagamentoFinanciadoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNomePagamentoFinanciado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputQuantidadeParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(btnLimparCamposFinanciado))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PagamentoFinanciadoLayout.setVerticalGroup(
            PagamentoFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagamentoFinanciadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PagamentoFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inputNomePagamentoFinanciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(inputTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(inputQuantidadeParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparCamposFinanciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PagamentoFinanciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesselecionarFinanciado)
                    .addComponent(btnCriarFinanciado)
                    .addComponent(btnAtualizarFinanciado)
                    .addComponent(btnExcluirFinanciado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        Main.add(PagamentoFinanciado, "cardFinanciado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinaciadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinaciadoMouseClicked
        // TODO add your handling code here:
        cl.show(Main, "cardFinanciado");

        btnAvista.setBackground(colorDisabled);
        btnFinaciado.setBackground(colorEnable);

        listarPagamentoFinanciado();
    }//GEN-LAST:event_btnFinaciadoMouseClicked

    private void btnAvistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvistaMouseClicked
        // TODO add your handling code here:
        cl.show(Main, "cardAvista");

        btnAvista.setBackground(colorEnable);
        btnFinaciado.setBackground(colorDisabled);

        listarPagamentoAvista();
    }//GEN-LAST:event_btnAvistaMouseClicked

    //Ações da forma de pagamento a vista.
    private void inputPercentualDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPercentualDescontoKeyTyped
        // TODO add your handling code here:
        if(inputPercentualDesconto.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_inputPercentualDescontoKeyTyped

    private void tabelaAvistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAvistaMouseClicked
        // TODO add your handling code here:
        if(tabelaAvista.getSelectedRow() != -1) {
            inserirDadosAvista();
        }
    }//GEN-LAST:event_tabelaAvistaMouseClicked

    private void btnLimparCamposAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposAvistaActionPerformed
        // TODO add your handling code here:
        limparCamposAvista();
    }//GEN-LAST:event_btnLimparCamposAvistaActionPerformed

    private void btnDesselecionarAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesselecionarAvistaActionPerformed
        // TODO add your handling code here:
        tabelaAvista.clearSelection();
    }//GEN-LAST:event_btnDesselecionarAvistaActionPerformed

    private void btnCriarAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAvistaActionPerformed
        // TODO add your handling code here:
        PagamentoAvista pagamentoAvista = leituraInputAvista();
        if(pagamentoAvista == null) {
            return;
        }
        
        System.out.println(avistaRepository.createPagamentoAvista(pagamentoAvista));
        listarPagamentoAvista();
        limparCamposAvista();
        JOptionPane.showMessageDialog(null, "Pagamento criado com sucesso!");
    }//GEN-LAST:event_btnCriarAvistaActionPerformed

    private void btnAtualizarAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarAvistaActionPerformed
        // TODO add your handling code here:
        if(tabelaAvista.getSelectedRow() != -1) {
            int cod = Integer.parseInt(tabelaAvista.getValueAt(tabelaAvista.getSelectedRow(), 0).toString());
            PagamentoAvista pagamentoAvista = leituraInputAvistaUpdate(cod);
            if(pagamentoAvista == null) {
                return;
            }

            avistaRepository.updatePagamentoAvista(pagamentoAvista);
            listarPagamentoAvista();
            limparCamposAvista();
            JOptionPane.showMessageDialog(null, "Pagamento atualizado com sucesso!");
        }
    }//GEN-LAST:event_btnAtualizarAvistaActionPerformed

    private void btnExcluirAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAvistaActionPerformed
        // TODO add your handling code here:
        if(tabelaAvista.getSelectedRow() != -1) {
            int cod = (int)tabelaAvista.getValueAt(tabelaAvista.getSelectedRow(), 0);
            int saida = JOptionPane.showInternalConfirmDialog(null, "Tem certeza de excluir essa Forma de pagamento?", "Excluindo Forma de pagamento",0);
            if(saida == 0) {
                if(formaPagamento.deleteFormaPagamento(cod)) {
                    listarPagamentoAvista();
                    limparCamposAvista();
                    JOptionPane.showInternalMessageDialog(null, "Forma pagamento excluida com sucesso!!");
                } else {
                    JOptionPane.showInternalMessageDialog(null, "Houve algo ao excluir Forma de pagamento. Pode ser o motivo de está em uso.");
                }
            }            
        } else {
            JOptionPane.showInternalMessageDialog(null, "É preciso selecionar uma linha na tabela para excluir uma Forma de pagamento.");
        }
    }//GEN-LAST:event_btnExcluirAvistaActionPerformed

    // Ações da forma de pagamento financiado
    private void btnDesselecionarFinanciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesselecionarFinanciadoActionPerformed
        // TODO add your handling code here:
        tabelaFinanciado.clearSelection();
    }//GEN-LAST:event_btnDesselecionarFinanciadoActionPerformed

    private void tabelaFinanciadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFinanciadoMouseClicked
        // TODO add your handling code here:
        if(tabelaFinanciado.getSelectedRow() != -1) {
            inserirDadosFinanciado();
        }
    }//GEN-LAST:event_tabelaFinanciadoMouseClicked

    private void btnLimparCamposFinanciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposFinanciadoActionPerformed
        // TODO add your handling code here:
        limparCamposFinanciado();
    }//GEN-LAST:event_btnLimparCamposFinanciadoActionPerformed

    private void btnCriarFinanciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarFinanciadoActionPerformed
        // TODO add your handling code here:
        PagamentoFinanciado pagamentoFinanciado = leituraInputFinanciado();
        if(pagamentoFinanciado == null) {
            return;
        }
        
        finaciadoRepository.createPagamentoFinanciado(pagamentoFinanciado);
        listarPagamentoFinanciado();
        limparCamposFinanciado();
        JOptionPane.showMessageDialog(null, "Pagamento criado com sucesso!");
    }//GEN-LAST:event_btnCriarFinanciadoActionPerformed

    private void btnAtualizarFinanciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarFinanciadoActionPerformed
        // TODO add your handling code here:
        if(tabelaFinanciado.getSelectedRow() != -1) {
            int cod = Integer.parseInt(tabelaFinanciado.getValueAt(tabelaFinanciado.getSelectedRow(), 0).toString());
            PagamentoFinanciado pagamentoFinanciado = leituraInputFinanciadoUpdate(cod);
            if(pagamentoFinanciado == null) {
                return;
            }

            finaciadoRepository.updatePagamentoFinanciado(pagamentoFinanciado);
            listarPagamentoFinanciado();
            limparCamposFinanciado();
            JOptionPane.showMessageDialog(null, "Pagamento atualizado com sucesso!");
        }
    }//GEN-LAST:event_btnAtualizarFinanciadoActionPerformed

    private void btnExcluirFinanciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFinanciadoActionPerformed
        // TODO add your handling code here:
        if(tabelaFinanciado.getSelectedRow() != -1) {
            int cod = (int)tabelaFinanciado.getValueAt(tabelaFinanciado.getSelectedRow(), 0);
            int saida = JOptionPane.showInternalConfirmDialog(null, "Tem certeza de excluir essa Forma de pagamento", "Excluindo Forma de pagamento",0);
            if(saida == 0) {
                if(formaPagamento.deleteFormaPagamento(cod)) {
                    listarPagamentoFinanciado();
                    limparCamposFinanciado();
                    JOptionPane.showInternalMessageDialog(null, "Forma pagamento excluida com sucesso!!");
                } else {
                    JOptionPane.showInternalMessageDialog(null, "Houve algo ao excluir Forma de pagamento. Pode ser o motivo de está em uso.");
                }
            }            
        } else {
            JOptionPane.showInternalMessageDialog(null, "É preciso selecionar uma linha na tabela para excluir uma Forma de pagamento.");
        }
    }//GEN-LAST:event_btnExcluirFinanciadoActionPerformed

    
    // Métodos de Pagamento A vista
    public void listarPagamentoAvista() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaAvista.getModel();
        modelo.setNumRows(0);
        for (PagamentoAvista avista : avistaRepository.getAll()) {
            modelo.addRow(new Object[]{
                avista.getId(),
                avista.getNome(),
                avista.getPercentualDisconto()
            });
        }
    }
    
    public void limparCamposAvista() {
        inputNomePagamentoAvista.setText("");
        inputPercentualDesconto.setText("");
    }
    
    public void inserirDadosAvista() {
        inputNomePagamentoAvista.setText((String) tabelaAvista.getValueAt(tabelaAvista.getSelectedRow(), 1));
        inputPercentualDesconto.setText(tabelaAvista.getValueAt(tabelaAvista.getSelectedRow(), 2).toString());
    }
    
    public PagamentoAvista leituraInputAvista() {
        String nome = inputNomePagamentoAvista.getText();
        if(nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "O nome do pagamento está vazio.");
            return null;
        }
        if(formaPagamento.getIdFormaPagamento(nome) != -1) {
            JOptionPane.showMessageDialog(null, "Forma de Pagamento já criada.");
            return null;
        }
            
        double percentualDesconto;
        try{
            percentualDesconto = Double.parseDouble(inputPercentualDesconto.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O percentual de desconto tem que ser em números.");
            return null;
        }
        
        return new PagamentoAvista(nome, percentualDesconto);
    }
    
    public PagamentoAvista leituraInputAvistaUpdate(int codPagamento) {
        PagamentoAvista pagamentoAvista = avistaRepository.getPagamentoAvista(codPagamento);
        if(pagamentoAvista == null) {
            JOptionPane.showMessageDialog(null, "Pagamento não encontrado");
            return null;
        }
        
        String nome = inputNomePagamentoAvista.getText();
        if(nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "O nome do pagamento está vazio.");
            return null;
        }
            
        double percentualDesconto;
        try{
            percentualDesconto = Double.parseDouble(inputPercentualDesconto.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O percentual de desconto tem que ser em números.");
            return null;
        }
        
        pagamentoAvista.setNome(nome);
        pagamentoAvista.setPercentualDisconto(percentualDesconto);
        
        return pagamentoAvista;
    }
    
    // Métodos de Pagamento Financiado
    public void listarPagamentoFinanciado() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaFinanciado.getModel();
        modelo.setNumRows(0);
        for (PagamentoFinanciado financiado : finaciadoRepository.getAll()) {
            modelo.addRow(new Object[]{
                financiado.getId(),
                financiado.getNome(),
                financiado.getTaxaJuros(),
                financiado.getQuantidadeParcelas()
            });
        }
    }
    
    public void inserirDadosFinanciado() {
        inputNomePagamentoFinanciado.setText((String) tabelaFinanciado.getValueAt(tabelaFinanciado.getSelectedRow(), 1));
        inputTaxaJuros.setText(tabelaFinanciado.getValueAt(tabelaFinanciado.getSelectedRow(), 2).toString());
        inputQuantidadeParcela.setText(tabelaFinanciado.getValueAt(tabelaFinanciado.getSelectedRow(),3).toString());
    }
    
    public void limparCamposFinanciado() {
        inputNomePagamentoFinanciado.setText("");
        inputTaxaJuros.setText("");
        inputQuantidadeParcela.setText("");
    }
    
    public PagamentoFinanciado leituraInputFinanciado() {
        String nome = inputNomePagamentoFinanciado.getText();
        if(nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "O nome do pagamento está vazio.");
            return null;
        }
        if(formaPagamento.getIdFormaPagamento(nome) != -1) {
            JOptionPane.showMessageDialog(null, "Forma de Pagamento já criado.");
            return null;
        }
            
        double taxaJuros;
        try{
            taxaJuros = Double.parseDouble(inputTaxaJuros.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A taxa de Juros tem que ser em números.");
            return null;
        }
        
        int qtdParcelas;
        try{
            qtdParcelas = Integer.parseInt(inputQuantidadeParcela.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A Quantidade de parcelas tem que ser em números.");
            return null;
        }
        
        return new PagamentoFinanciado(nome, taxaJuros, qtdParcelas);
    }
    
    public PagamentoFinanciado leituraInputFinanciadoUpdate(int codigo) {
        PagamentoFinanciado pagamentoFinanciado = finaciadoRepository.getPagamentoFinanciado(codigo);
        if(pagamentoFinanciado == null) {
            JOptionPane.showMessageDialog(null, "Pagamento não encontrado");
            return null;
        }
        
        String nome = inputNomePagamentoFinanciado.getText();
        if(nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "O nome do pagamento está vazio.");
            return null;
        }
            
        double taxaJuros;
        try{
            taxaJuros = Double.parseDouble(inputTaxaJuros.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A taxa de Juros tem que ser em números.");
            return null;
        }
        
        int qtdParcelas;
        try{
            qtdParcelas = Integer.parseInt(inputQuantidadeParcela.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A Quantidade de parcelas tem que ser em números.");
            return null;
        }
        
        pagamentoFinanciado.setNome(nome);
        pagamentoFinanciado.setTaxaJuros(taxaJuros);
        pagamentoFinanciado.setQuantiadeParcelas(qtdParcelas);
        
        return pagamentoFinanciado;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarFormasPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JPanel PagamentoAvista;
    private javax.swing.JPanel PagamentoFinanciado;
    private javax.swing.JButton btnAtualizarAvista;
    private javax.swing.JButton btnAtualizarFinanciado;
    private javax.swing.JPanel btnAvista;
    private javax.swing.JButton btnCriarAvista;
    private javax.swing.JButton btnCriarFinanciado;
    private javax.swing.JButton btnDesselecionarAvista;
    private javax.swing.JButton btnDesselecionarFinanciado;
    private javax.swing.JButton btnExcluirAvista;
    private javax.swing.JButton btnExcluirFinanciado;
    private javax.swing.JPanel btnFinaciado;
    private javax.swing.JButton btnLimparCamposAvista;
    private javax.swing.JButton btnLimparCamposFinanciado;
    private javax.swing.JTextField inputNomePagamentoAvista;
    private javax.swing.JTextField inputNomePagamentoFinanciado;
    private javax.swing.JTextField inputPercentualDesconto;
    private javax.swing.JTextField inputQuantidadeParcela;
    private javax.swing.JTextField inputTaxaJuros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel navbar;
    private javax.swing.JTable tabelaAvista;
    private javax.swing.JTable tabelaFinanciado;
    // End of variables declaration//GEN-END:variables
}
